### ISSUE TITLE
How to contribute exercices on http://www.france-ioi.org

### ISSUE THREAD

**Issue by ffries** [France-ioi/projects-overview#1]
Hello,

Could you elaborate how to contribute exercices on http://www.france-ioi.org?
I would love to see Capes exercices on france-ioi.org and might implement them if you explain how to code them.

Kind regards,

**Comment by mathias-hiron** [comment]
Hello,

We talked on the phone, and I'll give you the access needed to contribute to the new version of the platform. Thanks a lot for offering your contribution!

Best regards,
Mathias
